"""Tests for knowl.agents.dispatch — CLAUDE.md generation and agent dispatch."""

from unittest.mock import patch

import pytest

from knowl.context import store
from knowl.agents.dispatch import (
    generate_claude_md,
    write_claude_md,
    detect_agents,
    list_agents,
    dispatch,
    DispatchResult,
    AGENTS,
)


@pytest.fixture(autouse=True)
def use_tmp_knowl_dir(tmp_path):
    store.set_knowl_dir(tmp_path / ".knowl")
    store.init_store()
    yield


class TestGenerateClaudeMd:
    def test_empty_context(self):
        result = generate_claude_md()
        assert result == ""

    def test_with_global_context(self):
        (store.GLOBAL_DIR / "identity.md").write_text("# Identity\n\nI am a developer.")
        result = generate_claude_md()
        assert "Project Context (generated by Knowl)" in result
        assert "global/identity.md" in result
        assert "I am a developer." in result

    def test_with_project_context(self):
        store.create_project("my-app")
        (store.GLOBAL_DIR / "identity.md").write_text("# Me\nDeveloper")
        (store.PROJECTS_DIR / "my-app" / "arch.md").write_text("# Architecture\nFastAPI backend")
        store.set_active_files("my-app", ["project.md", "arch.md"])

        result = generate_claude_md("my-app")
        assert "global/identity.md" in result
        assert "project/arch.md" in result
        assert "FastAPI backend" in result

    def test_auto_generated_notice(self):
        (store.GLOBAL_DIR / "identity.md").write_text("# Identity")
        result = generate_claude_md()
        assert "auto-generated by Knowl" in result

    def test_respects_token_budget(self):
        (store.GLOBAL_DIR / "big.md").write_text("x" * 10000)
        result = generate_claude_md(token_budget=100)
        # Should still produce output (truncated)
        assert len(result) > 0


class TestWriteClaudeMd:
    def test_writes_file(self, tmp_path):
        (store.GLOBAL_DIR / "identity.md").write_text("# Identity\nTest user")
        path = write_claude_md(tmp_path)
        assert path.exists()
        assert path.name == "CLAUDE.md"
        content = path.read_text()
        assert "Test user" in content

    def test_overwrites_existing(self, tmp_path):
        (tmp_path / "CLAUDE.md").write_text("old content")
        (store.GLOBAL_DIR / "identity.md").write_text("# New")
        path = write_claude_md(tmp_path)
        assert "old content" not in path.read_text()
        assert "New" in path.read_text()


class TestDetectAgents:
    def test_returns_all_registered(self):
        agents = detect_agents()
        assert "claude-code" in agents
        assert "aider" in agents

    def test_checks_availability(self):
        agents = detect_agents()
        # Both may or may not be available in test env
        for key, agent in agents.items():
            assert isinstance(agent.available, bool)

    @patch("shutil.which", return_value="/usr/bin/claude")
    def test_detects_installed(self, mock_which):
        agents = detect_agents()
        assert agents["claude-code"].available is True


class TestListAgents:
    def test_returns_list(self):
        agents = list_agents()
        assert isinstance(agents, list)
        assert len(agents) >= 2
        keys = [a["key"] for a in agents]
        assert "claude-code" in keys
        assert "aider" in keys


class TestDispatch:
    def test_unknown_agent(self):
        result = dispatch("nonexistent", "do something")
        assert not result.success
        assert "Unknown agent" in result.error

    def test_dry_run(self, tmp_path):
        (store.GLOBAL_DIR / "identity.md").write_text("# Me")
        result = dispatch(
            "claude-code",
            "fix the bug",
            working_dir=tmp_path,
            dry_run=True,
        )
        assert result.success
        assert "Would run" in result.output
        assert "claude" in result.output
        assert "fix the bug" in result.output

    def test_dry_run_writes_claude_md(self, tmp_path):
        (store.GLOBAL_DIR / "identity.md").write_text("# Me")
        result = dispatch(
            "claude-code",
            "fix the bug",
            working_dir=tmp_path,
            dry_run=True,
        )
        assert result.context_file
        assert (tmp_path / "CLAUDE.md").exists()

    def test_agent_not_available(self):
        result = dispatch("claude-code", "do something")
        # Claude Code may or may not be installed; if it fails that's expected
        # (could be "not found on PATH" or "cannot be launched inside another session")
        assert isinstance(result, DispatchResult)

    @patch("subprocess.run")
    @patch("shutil.which", return_value="/usr/bin/claude")
    def test_successful_dispatch(self, mock_which, mock_run, tmp_path):
        mock_run.return_value = type("Result", (), {
            "returncode": 0,
            "stdout": "Task completed successfully.",
            "stderr": "",
        })()

        (store.GLOBAL_DIR / "identity.md").write_text("# Me")
        result = dispatch(
            "claude-code",
            "add tests",
            working_dir=tmp_path,
        )
        assert result.success
        assert result.output == "Task completed successfully."
        mock_run.assert_called_once()

    @patch("subprocess.run")
    @patch("shutil.which", return_value="/usr/bin/claude")
    def test_failed_dispatch(self, mock_which, mock_run, tmp_path):
        mock_run.return_value = type("Result", (), {
            "returncode": 1,
            "stdout": "",
            "stderr": "Something went wrong.",
        })()

        result = dispatch(
            "claude-code",
            "bad task",
            working_dir=tmp_path,
        )
        assert not result.success
        assert "Something went wrong" in result.error

    @patch("subprocess.run", side_effect=FileNotFoundError())
    @patch("shutil.which", return_value="/usr/bin/claude")
    def test_command_not_found_at_runtime(self, mock_which, mock_run, tmp_path):
        result = dispatch("claude-code", "task", working_dir=tmp_path)
        assert not result.success
        assert "Command not found" in result.error
