"""Agent dispatch — export context and launch coding agents with tasks."""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from knowl.context import store
from knowl.llm import claude
from knowl.log import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# CLAUDE.md generation
# ---------------------------------------------------------------------------

def generate_claude_md(
    project_name: str | None = None,
    token_budget: int = 8000,
) -> str:
    """Generate CLAUDE.md content from assembled context.

    Formats the active context (global + project) into a markdown file
    that Claude Code reads as its project context.
    """
    context_pieces = store.assemble_context(project_name, token_budget=token_budget)
    if not context_pieces:
        return ""

    sections: list[str] = []
    sections.append("# Project Context (generated by Knowl)\n")
    sections.append(
        "> This file was auto-generated by Knowl. "
        "Edit your context in ~/.knowl/ and re-export.\n"
    )

    for piece in context_pieces:
        source = piece.get("source", "unknown")
        content = piece.get("content", "").strip()
        if content:
            sections.append(f"## {source}\n\n{content}\n")

    return "\n".join(sections)


def write_claude_md(
    target_dir: Path,
    project_name: str | None = None,
    token_budget: int = 8000,
) -> Path:
    """Write a CLAUDE.md file into the target directory.

    Returns the path to the written file.
    """
    content = generate_claude_md(project_name, token_budget)
    target = target_dir / "CLAUDE.md"
    target.write_text(content, encoding="utf-8")
    logger.info("Wrote CLAUDE.md to %s", target)
    return target


# ---------------------------------------------------------------------------
# Agent registry
# ---------------------------------------------------------------------------

@dataclass
class AgentConfig:
    """Configuration for a supported coding agent."""
    name: str
    command: str                   # base command (e.g., "claude", "aider")
    context_flag: str = ""         # CLI flag for passing context (if any)
    context_method: str = "file"   # "file" (CLAUDE.md), "flag", or "stdin"
    available: bool = False        # detected at runtime


# Built-in agent definitions
AGENTS: dict[str, AgentConfig] = {
    "claude-code": AgentConfig(
        name="Claude Code",
        command="claude",
        context_method="file",  # uses CLAUDE.md
    ),
    "aider": AgentConfig(
        name="Aider",
        command="aider",
        context_flag="--message",
        context_method="flag",
    ),
}


def detect_agents() -> dict[str, AgentConfig]:
    """Check which agents are installed and available on PATH."""
    result: dict[str, AgentConfig] = {}
    for key, agent in AGENTS.items():
        agent_copy = AgentConfig(
            name=agent.name,
            command=agent.command,
            context_flag=agent.context_flag,
            context_method=agent.context_method,
            available=shutil.which(agent.command) is not None,
        )
        result[key] = agent_copy
    return result


def list_agents() -> list[dict[str, Any]]:
    """Return a list of agent info dicts for display."""
    agents = detect_agents()
    return [
        {
            "key": key,
            "name": agent.name,
            "command": agent.command,
            "available": agent.available,
        }
        for key, agent in agents.items()
    ]


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

@dataclass
class DispatchResult:
    """Result of dispatching a task to an agent."""
    agent: str
    task: str
    success: bool
    output: str = ""
    error: str = ""
    context_file: str = ""


def dispatch(
    agent_key: str,
    task: str,
    working_dir: Path | None = None,
    project_name: str | None = None,
    token_budget: int = 8000,
    dry_run: bool = False,
) -> DispatchResult:
    """Dispatch a task to a coding agent with assembled Knowl context.

    Args:
        agent_key: Key from AGENTS registry (e.g., "claude-code").
        task: The task description to send to the agent.
        working_dir: Directory to run the agent in. Defaults to cwd.
        project_name: Knowl project for context assembly.
        token_budget: Token budget for context.
        dry_run: If True, show what would be run without executing.

    Returns:
        DispatchResult with output and status.
    """
    agents = detect_agents()
    agent = agents.get(agent_key)

    if not agent:
        return DispatchResult(
            agent=agent_key, task=task, success=False,
            error=f"Unknown agent: {agent_key}. Available: {', '.join(AGENTS.keys())}",
        )

    if not agent.available and not dry_run:
        return DispatchResult(
            agent=agent_key, task=task, success=False,
            error=f"Agent '{agent.name}' ({agent.command}) not found on PATH.",
        )

    wd = working_dir or Path.cwd()

    # Build context
    context_file = ""
    if agent.context_method == "file":
        # Write CLAUDE.md into working directory
        claude_md_path = write_claude_md(wd, project_name, token_budget)
        context_file = str(claude_md_path)

    # Build command
    cmd: list[str] = [agent.command]

    if agent_key == "claude-code":
        # claude --print for non-interactive, or just pass the task
        cmd.extend(["--print", task])
    elif agent.context_method == "flag" and agent.context_flag:
        cmd.extend([agent.context_flag, task])
    else:
        cmd.append(task)

    if dry_run:
        return DispatchResult(
            agent=agent_key, task=task, success=True,
            output=f"Would run: {' '.join(cmd)}\nIn: {wd}",
            context_file=context_file,
        )

    # Execute
    logger.info("Dispatching to %s: %s", agent.name, " ".join(cmd))
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(wd),
            capture_output=True,
            text=True,
            timeout=300,  # 5 minute timeout
        )
        return DispatchResult(
            agent=agent_key,
            task=task,
            success=proc.returncode == 0,
            output=proc.stdout,
            error=proc.stderr if proc.returncode != 0 else "",
            context_file=context_file,
        )
    except FileNotFoundError:
        return DispatchResult(
            agent=agent_key, task=task, success=False,
            error=f"Command not found: {agent.command}",
            context_file=context_file,
        )
    except subprocess.TimeoutExpired:
        return DispatchResult(
            agent=agent_key, task=task, success=False,
            error="Agent timed out after 300 seconds.",
            context_file=context_file,
        )
